version: "2"

services:
  web:
    image: openach/openach
    volumes:
      - ./runtime:/home/www/openach/protected/runtime
      - ./config:/home/www/openach/protected/config
      - ./ssl:/etc/ssl
    expose:
      - "80"
      - "443"

